cup/urls.py
from django.urls import path
from django.views.generic import DetailView, ListView

from .models import Cup
from .views import CupCreateView, DonCreateView, DonDispatchView, DonUpdateView

app_name = 'cup'
urlpatterns = [
    path('all', ListView.as_view(model=Cup), name='home'),
    path('add', CupCreateView.as_view(), name='add'),
    path('<str:slug>', DetailView.as_view(model=Cup), name='cup'),
    path('<str:slug>/don', DonDispatchView.as_view(), name='don'),
    path('<str:slug>/don/create', DonCreateView.as_view(), name='add_don'),
    path('<str:slug>/don/<int:pk>', DonUpdateView.as_view(), name='update_don'),
]

test_cup/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('cup/', include('cup.urls')),
    path('', RedirectView.as_view(pattern_name='cup:home')),
]

cup/models.py
from decimal import Decimal

from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from autoslug import AutoSlugField
from ndh.utils import query_sum


class Cup(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = AutoSlugField(populate_from='name', unique=True)
    mini = models.DecimalField(max_digits=8, decimal_places=2)
    clos = models.BooleanField(default=False)

    def __str__(self):
        return f'Cup pour {self.name}'

    def get_absolute_url(self):
        return reverse('cup:cup', kwargs={'slug': self.slug})

    def funded(self):
        return query_sum(self.don_set, 'maxi') >= self.mini

    def missing(self):
        return self.mini - query_sum(self.don_set, 'maxi')

    def effort(self):
        mini_sum = query_sum(self.don_set, 'mini')
        maxi_sum = query_sum(self.don_set, 'maxi')
        return (self.mini - mini_sum) / (maxi_sum - mini_sum)


class Don(models.Model):
    cup = models.ForeignKey(Cup, on_delete=models.PROTECT)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    maxi = models.DecimalField(max_digits=8, decimal_places=2)
    mini = models.DecimalField(max_digits=8, decimal_places=2, default=0)

    def __str__(self):
        return f'Don de {self.user.username} pour {self.cup.name}'

    def get_absolute_url(self):
        return self.cup.get_absolute_url()

    class Meta:
        unique_together = ('cup', 'user')

    def pays(self):
        return self.mini + Decimal(self.cup.effort() * (self.maxi - self.mini)).quantize(Decimal('.01'))

cup/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views.generic import CreateView, RedirectView, UpdateView
from django.views.generic.detail import SingleObjectMixin

from .models import Cup, Don


class CupCreateView(LoginRequiredMixin, CreateView):
    model = Cup
    fields = ['name', 'mini']


class DonDispatchView(LoginRequiredMixin, SingleObjectMixin, RedirectView):
    model = Cup

    def get_redirect_url(self, *args, **kwargs):
        cup = self.get_object()
        if cup.don_set.filter(user=self.request.user).exists():
            self.kwargs['pk'] = cup.don_set.filter(user=self.request.user).first().pk
            return reverse('cup:update_don', kwargs=self.kwargs)
        return reverse('cup:add_don', kwargs=self.kwargs)


class DonMixin(LoginRequiredMixin):
    model = Don
    fields = ['maxi', 'mini']

    def form_valid(self, form):
        form.instance.cup = get_object_or_404(Cup, slug=self.kwargs['slug'])
        form.instance.user = self.request.user
        return super().form_valid(form)


class DonCreateView(DonMixin, CreateView):
    pass


class DonUpdateView(DonMixin, UpdateView):
    pass

cup/templates/cup/cup_detail.html
{% extends "base.html" %}

{% block title %}{{ cup }}{% endblock %}

{% block content %}

<div>
  <h2>{{ cup.name }} - {{ cup.mini }} €</h2>
  {% with funded=cup.funded %}
  <p>{% if funded %}C’est bon ! Effort: {% widthratio cup.effort 1 100 %}% {% else %}Il manque encore {{ cup.missing }} €{% endif %}</p>
  <table class="table">
    <tr><th>User</th><th>maxi</th><th>mini</th>{% if funded %}<th>final</th>{% endif %}</tr>
    {% for don in cup.don_set.all %}
    <tr><td>{{ don.user }}</td><td>{{ don.maxi }}</td><td>{{ don.mini }}</td>{% if funded %}<td>{{ don.pays }}</td>{% endif %}</tr>
    {% empty %}
    <tr><td span="{% if funded %}4{% else %}3{% endif %}">Nothing yet</td></tr»
    {% endfor %}
  </table>
  {% endwith%}
<a href="{% url 'cup:don' slug=cup.slug %}">Donner</a>
<div>

{% endblock %}

cup/templates/cup/cup_form.html
form.html

cup/templates/cup/cup_list.html
{% extends "base.html" %}

{% block title %}Cups{% endblock %}

{% block content %}

{% for cup in object_list %}
<div>
  <h2>{{ cup.name }} - {{ cup.mini }} €</h2>
  <p><a href="{{ cup.get_absolute_url }}">Lien</a></p>
  <p>{% if cup.funded %}C’est bon !{% else %}Il manque encore {{ cup.missing }} €{% endif %}</p>
</div>
{% empty %}
<p>Il n’y a pas de ⊔ pour l’instant</p>
{% endfor %}

{% endblock %}

cup/templates/cup/don_form.html
form.html

cup/templates/cup/form.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
<form action="" method="post" class="form-horizontal">
  {% csrf_token %}
  {% bootstrap_form form layout="horizontal" %}
  {% buttons layout="horizontal" %}
  <button type="submit" class="btn btn-primary">Ok !</button>
  {% endbuttons %}
</form>
{% endblock %}

test_cup/templates/base.html
{% extends 'ndh.html' %}
{% load ndh %}

{% block pagetitle %}Cup{% endblock %}
{% block sitetitle %}Cup{% endblock %}
{% block navbarleft %}
{% navbar_item 'cup:add' 'New Cup' %}
{% endblock %}